# Generated by Django 4.2.1 on 2023-05-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/faces')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/license_plates')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference_image', models.ImageField(blank=True, null=True, upload_to='uploads/predictions')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicensePlatePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference_image', models.ImageField(blank=True, null=True, upload_to='uploads/predictions')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('license_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camdetect_api.licenseplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference_image', models.ImageField(blank=True, null=True, upload_to='uploads/predictions')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camdetect_api.face')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
