# Generated by Django 4.2.1 on 2023-06-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camdetect_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faces'),
        ),
        migrations.AlterField(
            model_name='faceprediction',
            name='inference_image',
            field=models.ImageField(blank=True, null=True, upload_to='predictions'),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='license_plates'),
        ),
        migrations.AlterField(
            model_name='licenseplateprediction',
            name='inference_image',
            field=models.ImageField(blank=True, null=True, upload_to='predictions'),
        ),
        migrations.AlterField(
            model_name='objectprediction',
            name='inference_image',
            field=models.ImageField(blank=True, null=True, upload_to='predictions'),
        ),
    ]
