# Generated by Django 4.2.1 on 2023-06-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camdetect_api", "0002_alter_face_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenseplate",
            name="image",
        ),
        migrations.AddField(
            model_name="licenseplate",
            name="plate_text",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
