# Generated by Django 4.2.1 on 2023-05-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camdetect_api', '0003_rename_data_face_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/faces'),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/license_plates'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/things'),
        ),
    ]
