# Generated by Django 4.2.1 on 2023-05-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camdetect_api', '0006_faceprediction_result_licenseplateprediction_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='user',
        ),
        migrations.RemoveField(
            model_name='licenseplate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='user',
        ),
    ]
